dist: xenial
sudo: true
language: python
python:
  - "3.7"
script:
    - set -e
    - export TAG=`if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "latest"; else echo branch-$(echo $TRAVIS_PULL_REQUEST_BRANCH | sed s:/:-:g); fi`
    - docker build -t eu.gcr.io/census-eq-ci/eq-survey-runner-benchmark:"$TAG" .
    - echo "$DOCKER_GCR_PASSWORD" | base64 --decode | docker login -u "$DOCKER_GCR_USERNAME" --password-stdin https://eu.gcr.io
    - echo "Pushing with tag [$TAG]"
    - docker push eu.gcr.io/census-eq-ci/eq-survey-runner-benchmark:"$TAG"
branches:
    only:
        - master
