apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "name" . }}-locust-node
  labels:
    app: {{ template "name" . }}
    component: locust-node
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
      component: locust-node
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: locust-node
        name: {{ template "name" . }}-locust-node
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.container.image }}"
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: HOST
              value: "{{ .Values.host }}"
            - name: REQUESTS_JSON
              value: "{{ .Values.requestsJson }}"
            - name: USER_WAIT_TIME_MIN_SECONDS
              value: "{{ .Values.userWaitTimeMinSeconds }}"
            - name: USER_WAIT_TIME_MAX_SECONDS
              value: "{{ .Values.userWaitTimeMaxSeconds }}"
            - name: LOCUST_OPTS
              value: "{{ .Values.locustOptions }}"
