name: Main

on:
  push:
    branches:
      - main
jobs:
  docker-push:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t onsdigital/eq-survey-runner-benchmark:latest .
      - name: Push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing with tag [latest]"
          docker push onsdigital/eq-survey-runner-benchmark:latest
