name: Master

on:
  push:
    branches:
      - master

jobs:
  docker-push:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t eu.gcr.io/census-eq-ci/eq-survey-runner-benchmark:latest .
      - name: Push
        run: |
          echo "$DOCKER_GCR_PASSWORD" | base64 --decode | docker login -u "$DOCKER_GCR_USERNAME" --password-stdin https://eu.gcr.io
          echo "Pushing with tag [latest]"
          docker push eu.gcr.io/census-eq-ci/eq-survey-runner-benchmark:latest